#define FLOW_TAP_TERM 150
#define CHORDAL_HOLD
#undef DEBOUNCE
#define DEBOUNCE 20

#undef TAPPING_TERM
#define TAPPING_TERM 280

#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "5V7AB/7vDOdo"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

